language: node_js
node_js:
  - '12'
dist: trusty
all_branches: true
jobs:
  include:
    # ======== Parte del frontend ========
    - language: node_js
      node_js:  '12'

      warnings_are_errors: false

      cache:
        directories:
          - node_modules

      before_install:
        - cd front_end

      script:
          - npm test
          - npm run build

      deploy:
        provider: heroku
        api_key: $APIKEYHEROKU
        app: construction-planning-frontend

    # ======== Parte de Backend ========
    - language: python
      dist: xenial
      python:
        - 3.8

      warnings_are_errors: false

      before_install:
        - cd back_end

      before_script:
        - pip install -r requirements.txt

      script:
        - python manage.py test

      deploy:
        provider: heroku
        api_key: $APIKEYHEROKU
        app: construction-planning-backend
