# Generated by Django 3.2 on 2021-04-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='materiales',
            fields=[
                ('material_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('material_nombre', models.CharField(max_length=50)),
                ('material_cantidad', models.IntegerField()),
                ('material_estado', models.IntegerField()),
            ],
            options={
                'db_table': 'materiales',
            },
        ),
    ]
