# Generated by Django 3.2 on 2021-04-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('cliente_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cliente_nombre', models.CharField(max_length=50)),
                ('cliente_nit', models.CharField(max_length=10, unique=True)),
                ('cliente_estado', models.IntegerField()),
                ('cliente_correo', models.EmailField(max_length=50)),
                ('cliente_direccion', models.CharField(max_length=50)),
                ('cliente_contrasena', models.CharField(max_length=256)),
            ],
        ),
    ]
