# Generated by Django 3.2 on 2021-04-21 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientes',
            table='clientes',
        ),
    ]
