# Generated by Django 3.2 on 2021-04-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proveedores',
            fields=[
                ('proveedor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('proveedor_nombre', models.CharField(max_length=50)),
                ('proveedor_nit', models.CharField(max_length=10, unique=True)),
                ('proveedor_direccion', models.CharField(max_length=50)),
                ('proveedor_correo', models.EmailField(max_length=50)),
                ('proveedor_celular', models.CharField(max_length=15)),
                ('proveedor_estado', models.IntegerField()),
            ],
            options={
                'db_table': 'provedores',
            },
        ),
    ]
