# Generated by Django 3.2 on 2021-04-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trabajadores',
            fields=[
                ('trabajador_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trabajador_nombre', models.CharField(max_length=50)),
                ('trabajador_apellido', models.CharField(max_length=50)),
                ('trabajador_documento', models.CharField(max_length=20)),
                ('trabajador_direccion', models.CharField(max_length=50)),
                ('trabajador_celular', models.CharField(max_length=15)),
                ('trabajador_contrasena', models.CharField(max_length=256)),
                ('trabajador_estado', models.IntegerField()),
            ],
            options={
                'db_table': 'trabajadores',
            },
        ),
    ]
