# Generated by Django 3.2 on 2021-04-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='obras',
            fields=[
                ('obra_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('obra_nombre', models.CharField(max_length=50)),
                ('obra_direccion', models.CharField(max_length=50)),
                ('obra_ciudad', models.CharField(max_length=50)),
                ('obra_estado', models.IntegerField()),
                ('obra_latitud', models.DecimalField(decimal_places=6, max_digits=8)),
                ('obra_longitud', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
            options={
                'db_table': 'obras',
            },
        ),
    ]
